interpreter = ["sh", "-euo", "pipefail", "-c"]

[[task]]
name = "engage"
group = "versions"
script = "engage --version"

[[task]]
name = "nix"
group = "versions"
script = "nix --version"

[[task]]
name = "direnv"
group = "versions"
script = "direnv --version"

[[task]]
name = "rustc"
group = "versions"
script = "rustc --version"

[[task]]
name = "cargo"
group = "versions"
script = "cargo --version"

[[task]]
name = "cargo-fmt"
group = "versions"
script = "cargo fmt --version"

[[task]]
name = "rustdoc"
group = "versions"
script = "rustdoc --version"

[[task]]
name = "cargo-clippy"
group = "versions"
script = "cargo clippy -- --version"

[[task]]
name = "nixpkgs-fmt"
group = "versions"
script = "nixpkgs-fmt --version 2> /dev/null"
# This always exits 1 for some reason
ignore = [ 1 ]

[[task]]
name = "markdownlint"
group = "versions"
script = "markdownlint --version"

[[task]]
name = "markdownlint"
group = "lints"
script = "markdownlint -i target ."

[[task]]
name = "nixpkgs-fmt"
group = "lints"
script = "nixpkgs-fmt --check ."

[[task]]
name = "cargo-fmt"
group = "lints"
script = "cargo fmt --check -- --color=always"

[[task]]
name = "cargo-doc"
group = "lints"
script = """
RUSTDOCFLAGS="-D warnings" cargo doc \
    --workspace \
    --no-deps \
    --document-private-items \
    --color always
"""

[[task]]
name = "cargo-clippy"
group = "lints"
script = "cargo clippy --workspace --all-targets --color=always -- -D warnings"

[[task]]
name = "cargo"
group = "tests"
script = "cargo test --workspace --all-targets --color=always -- --color=always"
